name: finance_app
description: Finance Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.2.2
  equatable: ^2.0.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  get: ^4.1.4
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  local_auth: ^1.1.6
  lottie: ^1.0.1
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/animations/
    - lib/ui/assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/ui/assets/launcher_icon/icon.png"
